### ISSUE TITLE
Leading slash in absolute paths is missing

### ISSUE THREAD

**Issue by xdavidel** [dhananjaylatkar/cscope_lsp#2]
I just had an option to use the LSP version of this plugin. (This is awesome btw!)

I have an issue in which when using a full path for cscope.files the leading "/" is missing and navigation
does not work anymore.

I.E: `/home/<user>/...` becomes `home/<user>/...`

This is easily fixed by using a relative path instead.
Still, I thought it is worth mentioning.

10x for the hard work!

**Comment by dhananjaylatkar** [comment]
Hey @xdavidel 

I have uploaded fix. Please check.

**Comment by xdavidel** [comment]
Looks OK to me! 10x
